### ISSUE TITLE
Develop Mobile Apps

### ISSUE THREAD

**Issue by khursani8** [khursani8/TTP#3]
Develop Frontend for Mobile apps

- [x] Create parking
- [x] Parking page
- [x] Extend parking
- [x] My Car
- [x] Parking History
- [x] Payment Option
- [x] NFC page
- [x] Login
- [x] Register
- [x] Home dashboard

**Comment by khursani8** [comment]
@redemption024 ko boleh tick ke benda tu?

**Comment by khursani8** [comment]
@redemption024 My tu page apa? Profile page ke?

**Comment by shahrilamrias** [comment]
@khursani8 My Car, haha fixed. and yes aku bole tick

**Comment by shahrilamrias** [comment]
Completed all pages
